<?xml version = "1.0" encoding = "utf-8" ?>
<description
        xmlns = "http://www.w3.org/ns/wsdl"
        targetNamespace = "http://www.sensors.com/"
        xmlns:tns = "http://www.sensors.com/"
        xmlns:xs = "http://www.w3.org/2001/XMLSchema"
        xmlns:whttp="http://www.w3.org/ns/wsdl/http">

  <interface name = "sensorInterface">
    <operation name = "fetchTemperature">
      <output messageLabel = "temperature" element = "xs:double"/>
    </operation>
    <operation name = "setScale">
      <input messageLabel = "scale" element = "xs:string"/>
    </operation>
  </interface>

  <binding name = "sensorApi"
           interface = "tns:sensorInterface"
           type = "http://www.w3.org/ns/wsdl/http">
    <operation ref = "tns:fetchTemperature" whttp:method = "GET"/>
    <operation ref = "tns:setScale" whttp:method = "PUT"/>
  </binding>

  <service name = "sensorService"
           interface = "tns:sensorInterface">
    <documentation>
      This service encapsulates a temperature sensor device. The device is capturing the temperature and offering it
      through a REST interface. The default scale of measure is Celsius. Other scales provided are Fahrenheit and Kelvin
      This sensor offers HTTP methods for fetching the current temperature measured by the sensor and setting the scale
      desired for the temperature data.
    </documentation>
    <endpoint name = "sensorEndpoint"
              binding = "tns:sensorApi"
              address = "http://sensors.com/temperature_sensor"/>
  </service>
</description>